<template lang="pug">
#info.page-region.fit-content
  h2 Your Info
  .privacy-notice.branding-font
    .icon: font-awesome-icon(icon="lock", size="xs")
    p.m-0 All info are stored locally on your device.
  h3 PromptPay
  .input
    label Name
    input(type="text", maxlength="50", v-model="userinfo.name", @input="updateUserinfo")
  .input
    label PromptPay ID
    input(type="number", maxlength="50", v-model="userinfo.promptpay.id", @input="updateUserinfo")
    span.help-text Phone number, national ID, or REF ID generated by your bank
  .msg This page has an auto-save feature! Go on, explore the app!
</template>

<script>
export default {
  computed: {
    userinfo () {
      return this.$store.state.userinfo
    }
  },
  methods: {
    updateUserinfo () {
      this.$store.dispatch('updateUserinfo', this.userinfo)
    }
  }
}
</script>

<style lang="scss">
@import '../_variables.scss';

.privacy-notice {
  background: $subtle-black;
  border-radius: 6px;
  padding: 8px;
  display: flex;
  p {
    color: $subtle-white;
    font-size: 14px;
  }
  .icon {
    display: flex;
    justify-content: center;
    padding-top: 2px;
    svg path {
      fill: #ffffff;
    }
    margin-right: 8px;
  }
}
</style>
