<template lang="pug">
#info.page-region.fit-content
  h2
    | Your Info
    |
    small.save-indicator.saving(v-if="isSaving") Saving...
    small.save-indicator(v-if="isSaved")  All changes are saved.
  h3 PromptPay
  .input
    label Name
    input(type="text", maxlength="50", v-model="userinfo.name", @input="updateUserinfo")
  .input
    label PromptPay ID
    input(type="number", maxlength="50", v-model="userinfo.promptpay.id", @input="updateUserinfo")
    span.help-text Phone number, national ID, or REF ID generated by your bank
  .privacy-notice.branding-font
    .icon: font-awesome-icon(icon="lock", size="xs")
    p.m-0.branding-font All info are stored locally on your device.
  //- .msg This page has an auto-save feature! Go on, explore the app!
</template>

<script>
export default {
  data: () => ({
    isSaving: false,
    isSaved: false
  }),
  computed: {
    userinfo () {
      return this.$store.state.userinfo
    }
  },
  methods: {
    updateUserinfo () {
      this.isSaving = true
      this.isSaved = false
      this.$store.dispatch('updateUserinfo', this.userinfo)
      setTimeout(() => {
        this.isSaving = false
        this.isSaved = true
      }, 500)
    }
  }
}
</script>

<style lang="scss">
@import '../_variables.scss';

@keyframes saving-anim{
  0%{
      opacity: 0.5;
      }
  50%{
      opacity: 0.25;
      }
}

.save-indicator {
  font-size: 12px;
  opacity: 0.5;
  &.saving {
    animation: saving-anim 1s infinite 0s ease-in-out;
  }
}

.privacy-notice {
  background: $subtle-black;
  border-radius: 6px;
  padding: 8px;
  display: flex;
  p {
    color: $subtle-white;
    font-size: 14px;
  }
  .icon {
    display: flex;
    justify-content: center;
    padding-top: 2px;
    svg path {
      fill: #ffffff;
    }
    margin-right: 8px;
  }
}
</style>
