<template lang="pug">
#info.page-region.fit-content
  h2 Your Info
  .privacy-notice.branding-font.mb-2
    .icon: PhLockSimpleDuotone.text-sm
    p.m-0.text-xs All info are stored locally on your device and they are auto-save, how cool is that.
  h3 PromptPay
  .input
    label Name
    input(type="text" maxlength="50" v-model="store.userinfo.name")
  .input
    label PromptPay ID
    input(type="text" maxlength="50" v-model="store.userinfo.promptpay.id")
    span.help-text Phone number, national ID, or REF ID generated by your bank
  .input
    label OpenAI API Key (Optional)
    input(type="password" v-model="store.userinfo.openaiKey" autocomplete="off")
    span.help-text Starts with "sk-". Enable receipt parsing capabilities, speed up your spliting process
</template>

<script setup lang="ts">
import PhLockSimpleDuotone from '~icons/ph/lock-simple-duotone'

const { store } = useStore()
</script>

<style lang="scss">
.privacy-notice {
  background: #212121;
  border-radius: 6px;
  padding: 8px;
  display: flex;
  p {
    color: #fafafa;
  }
  .icon {
    display: flex;
    justify-content: center;
    padding-top: 2px;
    svg path {
      fill: #ffffff;
    }
    margin-right: 8px;
  }
}
</style>
