<template lang="pug">
#info.page-region.fit-content
  h2 Your Info
  .privacy-notice.branding-font
    //- .icon: font-awesome-icon(icon="lock", size="xs") // TODO:
    p.m-0 All info are stored locally on your device.
  h3 PromptPay
  .input
    label Name
    input(type="text" maxlength="50" v-model="store.userinfo.name")
  .input
    label PromptPay ID
    input(type="text" maxlength="50" v-model="store.userinfo.promptpay.id")
    span.help-text Phone number, national ID, or REF ID generated by your bank
  .msg This page has an auto-save feature! Go on, explore the app!
</template>

<script setup lang="ts">
const { store } = useStore()
</script>

<style lang="scss">
.privacy-notice {
  background: #212121;
  border-radius: 6px;
  padding: 8px;
  display: flex;
  p {
    color: #fafafa;
    font-size: 14px;
  }
  .icon {
    display: flex;
    justify-content: center;
    padding-top: 2px;
    svg path {
      fill: #ffffff;
    }
    margin-right: 8px;
  }
}
</style>
